### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by ruizlenato** [paurieraf/lastfm-collage-generator#1]
```
    image = collage_generator.generate_top_albums_collage(user="RenatohRibeiro", cols=5, rows=5, period="7day")
TypeError: CollageGenerator.generate_top_albums_collage() got an unexpected keyword argument 'user'
```

hm

**Comment by paurieraf** [comment]
Hi @ruizlenato , I made a typo mistake in the README.md with the user parameter name as it is "username" instead.
The correct code would be:
`image = collage_generator.generate_top_albums_collage(username="RenatohRibeiro", cols=5, rows=5, period="7day")`
